package edu.uw.apl.vmvols.model;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import edu.uw.apl.vmvols.model.virtualbox.VDIDisk;
import edu.uw.apl.vmvols.model.virtualbox.VDIException;
import edu.uw.apl.vmvols.model.virtualbox.VBoxVM;
import edu.uw.apl.vmvols.model.vmware.VMDKDisk;
import edu.uw.apl.vmvols.model.vmware.VMDKException;
import edu.uw.apl.vmvols.model.vmware.VMwareVM;

abstract public class VirtualMachine {

	/**
	 * This should be the sole api method for generating
	 * VirtualMachines.  The user should never have to call any VBoxVM
	 * or VMwareVM methods directly.  Update as and when we
	 * accommodate more VM types (ha!)
	 */
	static public VirtualMachine create( File f ) throws IOException {
		if( VBoxVM.isVBox( f ) )
			return new VBoxVM( f );
		if( VMwareVM.isVMware( f ) )
			return new VMwareVM( f );
		File parent = f.getParentFile();
		if( VBoxVM.isVBox( parent ) )
			return new VBoxVM( parent );
		if( VMwareVM.isVMware( parent ) )
			return new VMwareVM( parent );

		if( f.isDirectory() )
			// Neither VM type we know about AND not a file, bail...
			return null;

		/*
		  If neither the supplied file nor its parent directory can be
		  classed as a true vm root dir, but we know we have a regular
		  file, we treat the supplied file as a standalone (orphan?)
		  vdi/vmdk as generated by e.g. packer (will be alongside an
		  .ovf file) or e.g. vagrant (will be alongside a .box file).
		  We then build a 'dummy' vm around that one file.
		*/
		VirtualDisk vd = null;
		String name = f.getName();
		if( false ) {
		} else if( name.endsWith( VDIDisk.FILESUFFIX ) ) {
			try {
				vd = VDIDisk.readFrom( f );
				int last = name.length() - VDIDisk.FILESUFFIX.length(); 
				name = name.substring( 0, last - 1 );
			} catch( VDIException e ) {
			}
		} else if( name.endsWith( VMDKDisk.FILESUFFIX ) ) {
			try {
				vd = VMDKDisk.readFrom( f );
				int last = name.length() - VMDKDisk.FILESUFFIX.length(); 
				name = name.substring( 0, last - 1 );
			} catch( VMDKException e ) {
			}
		}
		if( vd == null )
			return null;
		final VirtualDisk vdf = vd;
		final String namef = name;
		return new VirtualMachine() {
			@Override
			public String getName() {
				return namef;
			}
			
			@Override
			public List<VirtualDisk> getBaseDisks() {
				List<VirtualDisk> vds = new ArrayList<VirtualDisk>();
				vds.add( vdf );
				return vds;
			}
			
			@Override
			public List<VirtualDisk> getActiveDisks() {
				return getBaseDisks();
			}
		};
	}

	abstract public String getName();

	abstract public List<VirtualDisk> getBaseDisks();
	abstract public List<VirtualDisk> getActiveDisks();
}

// eof
