#!/bin/bash                                                                     
#
# Stuart Maclean: A driver script for VDCat, which streams the entire
# contents (from sector 0) of a VM virtual disk to stdout.  The
# 'active' snapshot is always chosen, reflecting the content of the
# virtual disk should the VM be powered on.
#
# Usage: vdcat /path/to/vm/disk.vdi
#
# Usage: vdcat /path/to/vm/disk.vmdk
#
# Usage: vdcat /path/to/vm/
#
# The last works only if the VM has a single hard drive, as most do.
#

DIRNAME=`dirname $0`
JARSHOME=$DIRNAME/target

ARTIFACT=vmvols-cli

# The Maven <version> becomes part of the final artifact name (the
# jar).  Rather than hard-coding it here, we locate the jar with the
# LATEST version. Thus we always run the LATEST code, should many
# (stale) versions be present.

JAR=`ls $JARSHOME | grep $ARTIFACT | sort -n -r | head -1`

PACKAGE=edu.uw.apl.vmvols.cli
CLAZZ=VDCat

exec java $JAVA_OPTS -classpath $JARSHOME/$JAR $PACKAGE.$CLAZZ "$@"

# eof
