#!/bin/bash                                                                     

DIRNAME=`dirname $0`
JARSHOME=$DIRNAME/target

ARTIFACT=vmvols-cli

# The Maven <version> becomes part of the final artifact name (the
# jar).  Rather than hard-coding it here, we locate the jar with the
# LATEST version. Thus we always run the LATEST code, should many
# (stale) versions be present.

JAR=`ls $JARSHOME | grep $ARTIFACT | sort -n -r | head -1`

PACKAGE=edu.uw.apl.vmvols.cli
CLAZZ=VDCat

exec java $JAVA_OPTS -classpath $JARSHOME/$JAR $PACKAGE.$CLAZZ "$@"

# eof
