#!/bin/bash                                                                     

# Stuart Maclean: A driver script for mounting VM disks on the host.
# Currently understands .vdi and .vmdk file formats, so should be able
# to handle VirtualBox and (non-esxi/vmfs) VMWare managed VMs.
#
# Usage: vmmount /path/to/vm1 (/path/to/vmN)* mountPoint
#
# For options, invoke with -h, e.g.
#
# vmmount -h

# If you were to move the jars to somewhere more 'permanent', perhaps
# /usr/share/java/, update JARSHOME accordingly.  We are just a local
# reference based on this script's location.

DIRNAME=`dirname $0`
JARSHOME=$DIRNAME/target

ARTIFACT=vmvols-fuse

# The Maven <version> becomes part of the final artifact name (the
# jar).  Rather than hard-coding a jar file name here, we locate the
# jar with the LATEST version. Thus we always run the LATEST code,
# should many (stale) versions be present.
JAR=`ls $JARSHOME | grep $ARTIFACT | sort -n -r | head -1`

JARPATH=$JARSHOME/$JAR
PACKAGE=edu.uw.apl.vmvols.fuse
CLAZZ=Main

#JAVA_OPTS="-Dlog4j.debug"

exec java $JAVA_OPTS -classpath $JARPATH $PACKAGE.$CLAZZ "$@"

# eof
